version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.6

references:
  workspace_root: &workspace_root
                    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
      root: .
      paths:
        - .

commands:
  terraform-init:
    description: "terraform init"
    parameters:
      dir:
        description: "Directory to run the command in"
        type: string
      account-id:
        description: "AWS Account ID"
        type: string
    steps:
      - run:
          name: terraform init
          command:  |
          cd << parameters.dir >>
          terraform init -input=false -backend-config="bucket=<< parameters.account-id >>-tfstate"
  terraform-apply:
    description: "terraform Apply"
    parameters:
      vars:
        description: "Terraform vars"
        type: string
        default: ""
      dir:
        description: "Directory to run the command in"
        type: string
    steps:
      - run:
          name: terraform apply
          command:  |
          cd << parameters.dir >>
          terraform apply -auto-approve -var="<< parameters.vars >>"

jobs:
  get-aws-account:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          command:  echo "export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $BASH_ENV
  ecs-cluster-terraform:
    working_directory: *workspace_root
    docker:
      - image: hashicorp/terraform:1.1.5
    steps:
      - checkout
      - run:
          name: ECS-CLUSTER terraform init & apply
          command:
            cd ./ecs-cluster/terraform
      - terraform-init:
          account-id: $(AWS_ACCOUNT_ID)
      - terraform-apply
      - run:
          name: get terraform outputs
          command: |
            terraform output image_repo_name > ../../image_repo_name
            terraform output image_repo_url > ../..image_repo_url
            cd ../..
      - *persist_to_workspace
  build-push-docker-image:
    docker:
      - image: amazon/aws-cli
    steps:
      - *attach_workspace
      - run:
          name: build and push docker image
          command: |
            account_id = $(AWS_ACCOUNT_ID)
            tag = $(echo $CIRCLE_SHA1 | cut -c 1-7)
            repository = $(cat image_repo_name)
            ./service/push_image "${account_id}" "${AWS_DEFAULT_REGION}" "${repository}" "${tag}"
      - *persist_to_workspace
  ecs-service-terraform:
    docker:
      - image: hashicorp/terraform:1.1.5
    steps:
      - *attach_workspace
      - run:
          name: ECS-Service terraform init & apply
          command: |
            cd ./service/terraform
      - terraform-init:
          account-id: $(AWS_ACCOUNT_ID)
      - terraform-apply:
          vars: service_image_url=$(cat image_repo_url):$(echo $CIRCLE_SHA1 | cut -c 1-7)
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - get-aws-account
      - ecs-cluster-terraform:
          requires:
            - get-aws-account
      - build-push-docker-image:
          requires:
            - ecs-cluster-terraform
      - ecs-service-terraform:
          requires:
            - build-push-docker-image