version: 2
orbs:
  aws-cli: circleci/aws-cli@2.0.6

jobs:
  ecs-cluster-terraform:
    filters:
      branches:
        only:
          - main
    working_directory: /tmp/project
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: ECS-CLUSTER terraform init & apply
          command: |
            account_id = $(aws sts get-caller-identity --query Account --output text)
            cd ./ecs-cluster/terraform
            terraform init -input=false -backend-config="bucket=${account_id}-tfstate"
            terraform apply -auto-approve
            cd ../..
            terraform output image_repo_name > image_repo_name
            terraform output image_repo_url > image_repo_url
      - persist_to_workspace:
          root: .
          paths:
            - .
  build-push-docker-image:
    - attach_workspace:
        at: .
    docker:
      - image: amazon/aws-cli
      - run:
          name: build and push docker image
          command: |
            account_id = $(aws sts get-caller-identity --query Account --output text)
            tag = $(echo $CIRCLE_SHA1 | cut -c 1-7)
            repository = $(cat image_repo_name)
            ./service/push_image "${account_id}" "${AWS_DEFAULT_REGION}" "${repository}" "${tag}"
      - persist_to_workspace:
          root: .
          paths:
            - .
  ecs-service-terraform:
    - attach_workspace:
        at: .
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - run:
          name: ECS-Service terraform init & apply
          command: |
            account_id = $(aws sts get-caller-identity --query Account --output text)
            cd ./service/terraform
            terraform init -input=false -backend-config="bucket=${account_id}-tfstate"
            terraform apply -auto-approve -var="service_image_url=$(cat image_repo_url):$(echo $CIRCLE_SHA1 | cut -c 1-7)"
            cd ../..
            terraform output image_repo_url > image_repo_url
      - persist_to_workspace:
          root: .
          paths:
            - .
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - ecs-cluster-terraform
      - build-push-docker-image:
          requires:
            - ecs-cluster-terraform
      - build-push-docker-image:
          requires:
            - build-push-docker-image